[runner]
fastReruns = true

[server]
runOnSave = true
headless = true
enableStaticServing = true

[theme]
primaryColor="#ac94c4"
backgroundColor="#ffffff"
secondaryBackgroundColor="#ffffff"
textColor="#31333F"
font="sans serif"
